### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by klauspost**
I created this branch for updating the documentation.

Please don't merge yet - but you are welcome to edit of course (which is why I put the branch here).

### CODE REVIEW

**Comment by klauspost** [comment]
Link to [README.md](https://github.com/pquerna/ffjson/blob/documentation-v1-updates/README.md)

**Comment by pquerna** [comment]
I think this is OK to merge?  Maybe I'll merge buffer pooling first... but close right?

**Comment by klauspost** [comment]
Also, Tip 1: Use the generated Marshal/Unmarshal should have PR #99 resolved.

**Comment by pquerna** [comment]
going to merge, then do a few quick edits in master.

**Pull request merged**
