### PR TITLE
Add Marshal/Unmarshal to ffjson package.

### PR DESCRIPTION
**Pull request by klauspost**
This is intended to fix the chichen&egg problem with using the generated functions directly.

There are functions to help testing.

### CODE REVIEW

**Comment by pquerna** [comment]
I kinda like this approach, though I've always thought of `fflib` as a thing for generated code to import, not something that users import.... Kinda pondering putting it in a different package prefix.  wdyt?

**Comment by klauspost** [comment]
Very good idea. That way the documentation (godoc) would also be much cleaner. 

Is it possible to just have it in "pquerna/ffjson"? Short import path+good package name.

**Comment by pquerna** [comment]
it can't be `pquerna/ffjson` because thats where the `package main` lives :cry:

**Comment by klauspost** [comment]
`pquerna/ffjson/ffjson`?

**Comment by pquerna** [comment]
seems the most reasonable I think.

**Comment by pquerna** [comment]
LGTM

**Pull request merged**
