### PR TITLE
Add escaping html option

### PR DESCRIPTION
**Pull request by croath**

### CODE REVIEW

**Comment by croath** [comment]
Hello here,

It's a new method since Go 1.7, but I found no way to make it work for both 1.5/1.6/1.7.
There's no preprocessor in Go so that I cannot do it during compiling. Checking version at runtime is a way but call methods via reflecting is quite slow. Even if the method won't be called with high frequency, it's still a little bit ugly.

I don't know if any other ways can help the pull request pass build under pre-1.7 version?

Thanks.

**Comment by pquerna** [comment]
I think i'm ok dropping support for go1.6 and bellow.   All of my stuff is on modern versions.

**Comment by pquerna** [comment]
Thanks!

**Comment by croath** [comment]
Thanks, @pquerna !

Everything looks good now after my modifying the travis-ci build file.
I didn't add test cases for the change because it's all running inside of the built-in encoder, tests seem to be unnessessary.

**Pull request merged**
