### PR TITLE
Add tests for string and omitempty tags, and fix issues found

### PR DESCRIPTION
**Pull request by klauspost**
This fixes:

* https://github.com/pquerna/ffjson/issues/76  (Omitempty on pointer to value should only omit if not nil)
* https://github.com/pquerna/ffjson/issues/81 (Different encoding of value)
* https://github.com/pquerna/ffjson/issues/75 (Pointer to string with tag "string" has a closing quotation.)

It adds (disabled) test for these issues:
* https://github.com/pquerna/ffjson/issues/82 (Decoder: Attempting to decode null value)
* https://github.com/pquerna/ffjson/issues/80 (Support "string" tag in decoder)

Sorry about the big blob, but keeping tests in sync was important for me.

### CODE REVIEW

**Comment by klauspost** [comment]
Interesting - it seems like "string" tag was changed in Golang 1.3 -> 1.4 to also include pointers.

This PR is equivalent to how 1.4 behaves. How should we proceed?

**Comment by pquerna** [comment]
1.4 behavior going forward makes sense for me.  Maybe we add a test.Skip() for go 1.3?

**Comment by klauspost** [comment]
ok, changed test to exclude go 1.2 and 1.3 - go version is a bit tricky, but this should catch most cases.

**Comment by pquerna** [comment]
huh, go version is not as nice as i would of hoped. bleh.

**Pull request merged**
