### PR TITLE
Support array decoding

### PR DESCRIPTION
**Pull request by korya**
This should fix https://github.com/pquerna/ffjson/issues/147

### CODE REVIEW

**Comment by korya** [comment]
This fix depends on array support in gofuzz, see https://github.com/google/gofuzz/pull/19.

**Comment by pquerna** [comment]
Thanks!  Would like to have the gofuzz pr merged so Travis keeps passing before merging.

**Comment by korya** [comment]
Sure. I'll update you, once https://github.com/google/gofuzz/pull/19 is merged

**Comment by korya** [comment]
@pquerna the tests fail for dev build of golang. The problem seems to not related to my changes.

**Comment by korya** [comment]
It looks like the testing failure on latest go existed even before my changes. Does not it make sense to remove `tip` from travis configuration?

**Comment by korya** [comment]
Guys, can you please review the PR? I have some more coming.

**Pull request merged**
