### PR TITLE
Add reusable Encoder API, similar to encoding/json

### PR DESCRIPTION
**Pull request by klauspost**
This also includes an async encoder that will encode objects from several goroutines to a single io.Writer.

The example on the from page would look like this - much cleaner, and similar to `encoding/json`.

```Go
import "github.com/pquerna/ffjson/ffjson"

func EncodeItems(items []Item, out io.Writer) {
    // We declare the buffer here, so it can be reused.
    var encoder := ffjson.NewEncoder(out)

    for _, item := range items {
        // Encode into the buffer
        _ = enc.Encode(&buffer)
    }
}
```.

### CODE REVIEW

**Comment by klauspost** [comment]
As a side note, the async encoder is designed so it is possible to extend it later and have several encoders running at once.

But for now, this allows you to encode while other stuff is running, as well as sending data from multiple goroutines. This could be used for logging, message processing, etc.

**Comment by pquerna** [comment]
`Encoder` makes sense to me.

`EncoderAsync` I'm having a harder time philosophically aligning with `ffjson`:

1) The standard-library doesn't include any equivalent, so we would be educating the world on *why* this interface is a good one.
2) It could be a separate library, with no performance penalty (uses no internals)
3) I can see some use cases for `EncoderAsync`, but it seems like often times you would want to have more direct control over concurrency and ordering in a real world application.

**Comment by klauspost** [comment]
I see your point. Actually, as you say, it could be a fine generic package, and it could even be used with encoding/json.

I will take it out of the PR tomorrow, and probably do a separate package.

**Comment by klauspost** [comment]
Async removed. I will merge the PR.

**Pull request merged**
