### PR TITLE
Convert strconv.AppendFloat to use the internal buffer for writing.

### PR DESCRIPTION
**Pull request by klauspost**
I just noticed this on #23 

This is pretty much the built-in function that writes directly to the buffer instead of a temporary byte array.

### CODE REVIEW

**Comment by pquerna** [comment]
`extfloat.go` is already in the `v1/internal` directory -- i'd like to put as many symbols as possible in internal / make them not public except for the AppendFloat function.

**Comment by klauspost** [comment]
Ah - I will move it tomorrow!

**Comment by klauspost** [comment]
I just checked. There aren't any new exported functions or variables, so it doesn't really make any difference. But I will move it, just so we don't have duplicate code.

**Comment by pquerna** [comment]
one other thought I had about this was to use the Buffer. Pool object, but use the 128 []byte arrays rather than having another pool... but maybe not worth messing with.

**Comment by pquerna** [comment]
Merged in 2df0f0d

**Pull request closed without merging**
